// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Archive struct { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L11)
	query *querybuilder.Selection

	id *ID
}

func (r *Archive) WithGraphQLQuery(q *querybuilder.Selection) *Archive {
	return &Archive{
		query: q,
	}
}

// A unique identifier for this Archive.
func (r *Archive) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Archive) XXX_GraphQLType() string {
	return "Archive"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Archive) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Archive) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Archive) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// ArchiveTarOpts contains options for Archive.Tar
type ArchiveTarOpts struct {
	Gzip bool // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L32)
}

func (r *Archive) Tar(directory *Directory, opts ...ArchiveTarOpts) *File { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L28)
	assertNotNil("directory", directory)
	q := r.query.Select("tar")
	for i := len(opts) - 1; i >= 0; i-- {
		// `gzip` optional argument
		if !querybuilder.IsZeroValue(opts[i].Gzip) {
			q = q.Arg("gzip", opts[i].Gzip)
		}
	}
	q = q.Arg("directory", directory)

	return &File{
		query: q,
	}
}

func (r *Archive) Untar(file *File) *Directory { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L54)
	assertNotNil("file", file)
	q := r.query.Select("untar")
	q = q.Arg("file", file)

	return &Directory{
		query: q,
	}
}

func (r *Archive) Zip(directory *Directory) *File { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L86)
	assertNotNil("directory", directory)
	q := r.query.Select("zip")
	q = q.Arg("directory", directory)

	return &File{
		query: q,
	}
}

// AsNode returns this Archive as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Archive) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Retrieve the binding value, as type Archive
func (r *Binding) AsArchive() *Archive { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L11)
	q := r.query.Select("asArchive")

	return &Archive{
		query: q,
	}
}

// Create or update a binding of type Archive in the environment
func (r *Env) WithArchiveInput(name string, value *Archive, description string) *Env { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L11)
	assertNotNil("value", value)
	q := r.query.Select("withArchiveInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Archive output to be assigned in the environment
func (r *Env) WithArchiveOutput(name string, description string) *Env { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L11)
	q := r.query.Select("withArchiveOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// ArchiveOpts contains options for Query.Archive
type ArchiveOpts struct {
	Container *Container // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L18)
}

func (r *Query) Archive(opts ...ArchiveOpts) *Archive { // archive (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/archive/main.go#L16)
	q := r.query.Select("archive")
	for i := len(opts) - 1; i >= 0; i-- {
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Archive{
		query: q,
	}
}
