// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Arch struct { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L9)
	query *querybuilder.Selection

	gnu       *string
	id        *ID
	microsoft *string
	oci       *string
}

func (r *Arch) WithGraphQLQuery(q *querybuilder.Selection) *Arch {
	return &Arch{
		query: q,
	}
}

// GNU returns the architecture in GNU/uname naming (e.g. "x86_64", "aarch64").
func (r *Arch) Gnu(ctx context.Context) (string, error) { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L38)
	if r.gnu != nil {
		return *r.gnu, nil
	}
	q := r.query.Select("gnu")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// A unique identifier for this Arch.
func (r *Arch) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Arch) XXX_GraphQLType() string {
	return "Arch"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Arch) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Arch) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Arch) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// Microsoft returns the architecture in Microsoft naming (e.g. "x64", "arm64").
func (r *Arch) Microsoft(ctx context.Context) (string, error) { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L54)
	if r.microsoft != nil {
		return *r.microsoft, nil
	}
	q := r.query.Select("microsoft")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// OCI returns the architecture in OCI/Go naming (e.g. "amd64", "arm64").
func (r *Arch) Oci(ctx context.Context) (string, error) { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L33)
	if r.oci != nil {
		return *r.oci, nil
	}
	q := r.query.Select("oci")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this Arch as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Arch) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// Retrieve the binding value, as type Arch
func (r *Binding) AsArch() *Arch { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L9)
	q := r.query.Select("asArch")

	return &Arch{
		query: q,
	}
}

// Create or update a binding of type Arch in the environment
func (r *Env) WithArchInput(name string, value *Arch, description string) *Env { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L9)
	assertNotNil("value", value)
	q := r.query.Select("withArchInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Arch output to be assigned in the environment
func (r *Env) WithArchOutput(name string, description string) *Env { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L9)
	q := r.query.Select("withArchOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

func (r *Query) Arch() *Arch { // arch (https://github.com/frantjc/daggerverse/tree/382d2a0f8aa4fdd0ba466d77fc3e2aea6eb5b245/arch/main.go#L16)
	q := r.query.Select("arch")

	return &Arch{
		query: q,
	}
}
