// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Go
func (r *Binding) AsGo() *Go { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L15)
	q := r.query.Select("asGo")

	return &Go{
		query: q,
	}
}

// Create or update a binding of type Go in the environment
func (r *Env) WithGoInput(name string, value *Go, description string) *Env { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L15)
	assertNotNil("value", value)
	q := r.query.Select("withGoInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Go output to be assigned in the environment
func (r *Env) WithGoOutput(name string, description string) *Env { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L15)
	q := r.query.Select("withGoOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Go struct { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L15)
	query *querybuilder.Selection

	id          *ID
	staticcheck *Void
	test        *Void
	vet         *Void
	vulncheck   *Void
}

func (r *Go) WithGraphQLQuery(q *querybuilder.Selection) *Go {
	return &Go{
		query: q,
	}
}

// GoBuildOpts contains options for Go.Build
type GoBuildOpts struct {

	// Default: "./"
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L95)

	// Default: "-s -w"
	Ldflags string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L98)

	Cgo bool // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L100)

	Goarch string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L102)

	Goos string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L104)
}

func (r *Go) Build(opts ...GoBuildOpts) *File { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L91)
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `ldflags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ldflags) {
			q = q.Arg("ldflags", opts[i].Ldflags)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `goarch` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goarch) {
			q = q.Arg("goarch", opts[i].Goarch)
		}
		// `goos` optional argument
		if !querybuilder.IsZeroValue(opts[i].Goos) {
			q = q.Arg("goos", opts[i].Goos)
		}
	}

	return &File{
		query: q,
	}
}

func (r *Go) Container() *Container { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L16)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// GoFmtOpts contains options for Go.Fmt
type GoFmtOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L176)
}

func (r *Go) Fmt(opts ...GoFmtOpts) *Changeset { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L172)
	q := r.query.Select("fmt")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
	}

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Go.
func (r *Go) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Go) XXX_GraphQLType() string {
	return "Go"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Go) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Go) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Go) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// GoStaticcheckOpts contains options for Go.Staticcheck
type GoStaticcheckOpts struct {

	// Default: "latest"
	Version string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L213)
}

func (r *Go) Staticcheck(ctx context.Context, opts ...GoStaticcheckOpts) error { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L209)
	if r.staticcheck != nil {
		return nil
	}
	q := r.query.Select("staticcheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// GoTestOpts contains options for Go.Test
type GoTestOpts struct {

	// Default: "./..."
	Pkg string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L142)

	Race bool // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L144)

	Cgo bool // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L146)

	Tags []string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L148)
}

func (r *Go) Test(ctx context.Context, opts ...GoTestOpts) error { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L138)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `pkg` optional argument
		if !querybuilder.IsZeroValue(opts[i].Pkg) {
			q = q.Arg("pkg", opts[i].Pkg)
		}
		// `race` optional argument
		if !querybuilder.IsZeroValue(opts[i].Race) {
			q = q.Arg("race", opts[i].Race)
		}
		// `cgo` optional argument
		if !querybuilder.IsZeroValue(opts[i].Cgo) {
			q = q.Arg("cgo", opts[i].Cgo)
		}
		// `tags` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tags) {
			q = q.Arg("tags", opts[i].Tags)
		}
	}

	return q.Execute(ctx)
}

func (r *Go) Tidy() *Changeset { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L223)
	q := r.query.Select("tidy")

	return &Changeset{
		query: q,
	}
}

func (r *Go) Vet(ctx context.Context) error { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L201)
	if r.vet != nil {
		return nil
	}
	q := r.query.Select("vet")

	return q.Execute(ctx)
}

// GoVulncheckOpts contains options for Go.Vulncheck
type GoVulncheckOpts struct {

	// Default: "latest"
	Version string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L191)
}

func (r *Go) Vulncheck(ctx context.Context, opts ...GoVulncheckOpts) error { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L187)
	if r.vulncheck != nil {
		return nil
	}
	q := r.query.Select("vulncheck")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return q.Execute(ctx)
}

// AsNode returns this Go as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Go) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// GoOpts contains options for Query.Go
type GoOpts struct {
	Workspace *Workspace // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L21)

	// Default: "."
	Path string // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L24)

	Container *Container // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L26)
}

// A generated module for Go functions
func (r *Query) Go(opts ...GoOpts) *Go { // go (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/go/main.go#L19)
	q := r.query.Select("go")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Go{
		query: q,
	}
}
