// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Mise
func (r *Binding) AsMise() *Mise { // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L144)
	q := r.query.Select("asMise")

	return &Mise{
		query: q,
	}
}

// Create or update a binding of type Mise in the environment
func (r *Env) WithMiseInput(name string, value *Mise, description string) *Env { // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L144)
	assertNotNil("value", value)
	q := r.query.Select("withMiseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Mise output to be assigned in the environment
func (r *Env) WithMiseOutput(name string, description string) *Env { // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L144)
	q := r.query.Select("withMiseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Mise struct { // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L144)
	query *querybuilder.Selection

	id *ID
}

func (r *Mise) WithGraphQLQuery(q *querybuilder.Selection) *Mise {
	return &Mise{
		query: q,
	}
}

// MiseContainerOpts contains options for Mise.Container
type MiseContainerOpts struct {
	NoEnv bool // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L189)

	NoHooks bool // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L191)

	Tools []string // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L193)

	Include []string // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L195)

	Container *Container // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L197)
}

func (r *Mise) Container(opts ...MiseContainerOpts) *Container { // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L186)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `noEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoEnv) {
			q = q.Arg("noEnv", opts[i].NoEnv)
		}
		// `noHooks` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoHooks) {
			q = q.Arg("noHooks", opts[i].NoHooks)
		}
		// `tools` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tools) {
			q = q.Arg("tools", opts[i].Tools)
		}
		// `include` optional argument
		if !querybuilder.IsZeroValue(opts[i].Include) {
			q = q.Arg("include", opts[i].Include)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Container{
		query: q,
	}
}

// A unique identifier for this Mise.
func (r *Mise) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Mise) XXX_GraphQLType() string {
	return "Mise"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Mise) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Mise) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Mise) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// AsNode returns this Mise as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Mise) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// MiseOpts contains options for Query.Mise
type MiseOpts struct {
	Workspace *Workspace // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L153)

	// Default: "."
	Path string // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L156)

	// Default: "2026.5.15"
	Version string // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L159)
}

func (r *Query) Mise(opts ...MiseOpts) *Mise { // mise (https://github.com/frantjc/daggerverse/tree/f22c1fc85dfa656d4216ea5a5086dee4eabefd5a/mise/main.go#L151)
	q := r.query.Select("mise")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Mise{
		query: q,
	}
}
