// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Mise
func (r *Binding) AsMise() *Mise { // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L145)
	q := r.query.Select("asMise")

	return &Mise{
		query: q,
	}
}

// Create or update a binding of type Mise in the environment
func (r *Env) WithMiseInput(name string, value *Mise, description string) *Env { // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L145)
	assertNotNil("value", value)
	q := r.query.Select("withMiseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Mise output to be assigned in the environment
func (r *Env) WithMiseOutput(name string, description string) *Env { // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L145)
	q := r.query.Select("withMiseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Mise struct { // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L145)
	query *querybuilder.Selection

	doctor *Void
	id     *ID
}

func (r *Mise) WithGraphQLQuery(q *querybuilder.Selection) *Mise {
	return &Mise{
		query: q,
	}
}

// MiseContainerOpts contains options for Mise.Container
type MiseContainerOpts struct {
	Workspace *Workspace // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L186)

	NoEnv bool // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L188)

	NoHooks bool // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L190)

	Tools []string // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L192)

	Include []string // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L194)

	Container *Container // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L196)
}

func (r *Mise) Container(opts ...MiseContainerOpts) *Container { // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L184)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `noEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoEnv) {
			q = q.Arg("noEnv", opts[i].NoEnv)
		}
		// `noHooks` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoHooks) {
			q = q.Arg("noHooks", opts[i].NoHooks)
		}
		// `tools` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tools) {
			q = q.Arg("tools", opts[i].Tools)
		}
		// `include` optional argument
		if !querybuilder.IsZeroValue(opts[i].Include) {
			q = q.Arg("include", opts[i].Include)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Container{
		query: q,
	}
}

// MiseDoctorOpts contains options for Mise.Doctor
type MiseDoctorOpts struct {
	Workspace *Workspace // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L359)

	NoEnv bool // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L361)

	NoHooks bool // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L363)

	Tools []string // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L365)

	Include []string // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L367)

	Container *Container // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L369)
}

func (r *Mise) Doctor(ctx context.Context, opts ...MiseDoctorOpts) error { // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L357)
	if r.doctor != nil {
		return nil
	}
	q := r.query.Select("doctor")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `noEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoEnv) {
			q = q.Arg("noEnv", opts[i].NoEnv)
		}
		// `noHooks` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoHooks) {
			q = q.Arg("noHooks", opts[i].NoHooks)
		}
		// `tools` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tools) {
			q = q.Arg("tools", opts[i].Tools)
		}
		// `include` optional argument
		if !querybuilder.IsZeroValue(opts[i].Include) {
			q = q.Arg("include", opts[i].Include)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return q.Execute(ctx)
}

// A unique identifier for this Mise.
func (r *Mise) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Mise) XXX_GraphQLType() string {
	return "Mise"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Mise) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Mise) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Mise) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// AsNode returns this Mise as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Mise) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// MiseOpts contains options for Query.Mise
type MiseOpts struct {
	Workspace *Workspace // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L152)

	// Default: "."
	Path string // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L155)

	// Default: "2026.5.15"
	Version string // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L158)
}

func (r *Query) Mise(opts ...MiseOpts) *Mise { // mise (https://github.com/frantjc/daggerverse/tree/d5754653df811e7ba6ea6bffa9fe08592b2d7a07/mise/main.go#L150)
	q := r.query.Select("mise")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
	}

	return &Mise{
		query: q,
	}
}
