// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type SindriDev
func (r *Binding) AsSindriDev() *SindriDev { // sindri-dev (../../.dagger/main.go:16:6)
	q := r.query.Select("asSindriDev")

	return &SindriDev{
		query: q,
	}
}

// Create or update a binding of type SindriDev in the environment
func (r *Env) WithSindriDevInput(name string, value *SindriDev, description string) *Env { // sindri-dev (../../.dagger/main.go:16:6)
	assertNotNil("value", value)
	q := r.query.Select("withSindriDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired SindriDev output to be assigned in the environment
func (r *Env) WithSindriDevOutput(name string, description string) *Env { // sindri-dev (../../.dagger/main.go:16:6)
	q := r.query.Select("withSindriDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// BinaryOpts contains options for Query.Binary
type BinaryOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:179:2)
}

func (r *Query) Binary(opts ...BinaryOpts) *File { // sindri-dev (../../.dagger/main.go:177:1)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	return &File{
		query: q,
	}
}

// ContainerOpts contains options for Query.Container
type ContainerOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:32:2)

	Module string // sindri-dev (../../.dagger/main.go:34:2)
}

func (r *Query) Container(opts ...ContainerOpts) *Container { // sindri-dev (../../.dagger/main.go:30:1)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Container{
		query: q,
	}
}

// ServiceOpts contains options for Query.Service
type ServiceOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:91:2)

	Backend string // sindri-dev (../../.dagger/main.go:93:2)

	Module string // sindri-dev (../../.dagger/main.go:95:2)
}

func (r *Query) Service(opts ...ServiceOpts) *Service { // sindri-dev (../../.dagger/main.go:89:1)
	q := r.query.Select("service")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `backend` optional argument
		if !querybuilder.IsZeroValue(opts[i].Backend) {
			q = q.Arg("backend", opts[i].Backend)
		}
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Service{
		query: q,
	}
}

// TagOpts contains options for Query.Tag
type TagOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:171:2)
}

func (r *Query) Tag(ctx context.Context, opts ...TagOpts) (string, error) { // sindri-dev (../../.dagger/main.go:169:1)
	q := r.query.Select("tag")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// TestOpts contains options for Query.Test
type TestOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:195:2)
}

func (r *Query) Test(ctx context.Context, opts ...TestOpts) error { // sindri-dev (../../.dagger/main.go:193:1)
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	return q.Execute(ctx)
}

// VersionOpts contains options for Query.Version
type VersionOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:138:2)
}

func (r *Query) Version(ctx context.Context, opts ...VersionOpts) (string, error) { // sindri-dev (../../.dagger/main.go:136:1)
	q := r.query.Select("version")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type SindriDev struct { // sindri-dev (../../.dagger/main.go:16:6)
	query *querybuilder.Selection

	id      *ID
	tag     *string
	test    *Void
	version *string
}

func (r *SindriDev) WithGraphQLQuery(q *querybuilder.Selection) *SindriDev {
	return &SindriDev{
		query: q,
	}
}

// SindriDevBinaryOpts contains options for SindriDev.Binary
type SindriDevBinaryOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:179:2)
}

func (r *SindriDev) Binary(opts ...SindriDevBinaryOpts) *File { // sindri-dev (../../.dagger/main.go:177:1)
	q := r.query.Select("binary")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	return &File{
		query: q,
	}
}

// SindriDevContainerOpts contains options for SindriDev.Container
type SindriDevContainerOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:32:2)

	Module string // sindri-dev (../../.dagger/main.go:34:2)
}

func (r *SindriDev) Container(opts ...SindriDevContainerOpts) *Container { // sindri-dev (../../.dagger/main.go:30:1)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Container{
		query: q,
	}
}

// A unique identifier for this SindriDev.
func (r *SindriDev) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *SindriDev) XXX_GraphQLType() string {
	return "SindriDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *SindriDev) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *SindriDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *SindriDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// SindriDevServiceOpts contains options for SindriDev.Service
type SindriDevServiceOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:91:2)

	Backend string // sindri-dev (../../.dagger/main.go:93:2)

	Module string // sindri-dev (../../.dagger/main.go:95:2)
}

func (r *SindriDev) Service(opts ...SindriDevServiceOpts) *Service { // sindri-dev (../../.dagger/main.go:89:1)
	q := r.query.Select("service")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
		// `backend` optional argument
		if !querybuilder.IsZeroValue(opts[i].Backend) {
			q = q.Arg("backend", opts[i].Backend)
		}
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Service{
		query: q,
	}
}

// SindriDevTagOpts contains options for SindriDev.Tag
type SindriDevTagOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:171:2)
}

func (r *SindriDev) Tag(ctx context.Context, opts ...SindriDevTagOpts) (string, error) { // sindri-dev (../../.dagger/main.go:169:1)
	if r.tag != nil {
		return *r.tag, nil
	}
	q := r.query.Select("tag")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// SindriDevTestOpts contains options for SindriDev.Test
type SindriDevTestOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:195:2)
}

func (r *SindriDev) Test(ctx context.Context, opts ...SindriDevTestOpts) error { // sindri-dev (../../.dagger/main.go:193:1)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	return q.Execute(ctx)
}

// SindriDevVersionOpts contains options for SindriDev.Version
type SindriDevVersionOpts struct {
	Workspace *Workspace // sindri-dev (../../.dagger/main.go:138:2)
}

func (r *SindriDev) Version(ctx context.Context, opts ...SindriDevVersionOpts) (string, error) { // sindri-dev (../../.dagger/main.go:136:1)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")
	for i := len(opts) - 1; i >= 0; i-- {
		// `workspace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Workspace) {
			q = q.Arg("workspace", opts[i].Workspace)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this SindriDev as a Node.
// This is a local type conversion — no GraphQL call.
func (r *SindriDev) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}
