// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Sindri
func (r *Binding) AsSindri() *Sindri { // sindri (../../modules/interface/main.go:15:6)
	q := r.query.Select("asSindri")

	return &Sindri{
		query: q,
	}
}

// Create or update a binding of type Sindri in the environment
func (r *Env) WithSindriInput(name string, value *Sindri, description string) *Env { // sindri (../../modules/interface/main.go:15:6)
	assertNotNil("value", value)
	q := r.query.Select("withSindriInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Sindri output to be assigned in the environment
func (r *Env) WithSindriOutput(name string, description string) *Env { // sindri (../../modules/interface/main.go:15:6)
	q := r.query.Select("withSindriOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// The interface that a Dagger module must implement to work with Sindri.
func (r *Query) Sindri() *Sindri { // sindri (../../modules/interface/main.go:15:6)
	q := r.query.Select("sindri")

	return &Sindri{
		query: q,
	}
}

type Sindri struct { // sindri (../../modules/interface/main.go:15:6)
	query *querybuilder.Selection

	id *ID
}

func (r *Sindri) WithGraphQLQuery(q *querybuilder.Selection) *Sindri {
	return &Sindri{
		query: q,
	}
}

// A unique identifier for this Sindri.
func (r *Sindri) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Sindri) XXX_GraphQLType() string {
	return "Sindri"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Sindri) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Sindri) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Sindri) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

func (r *Sindri) Image(name string, reference string) *Container { // sindri (../../modules/interface/main.go:17:1)
	q := r.query.Select("image")
	q = q.Arg("name", name)
	q = q.Arg("reference", reference)

	return &Container{
		query: q,
	}
}

// AsNode returns this Sindri as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Sindri) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}
