// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type SindriDev
func (r *Binding) AsSindriDev() *SindriDev { // sindri-dev (../../.dagger/main.go:16:6)
	q := r.query.Select("asSindriDev")

	return &SindriDev{
		query: q,
	}
}

// Create or update a binding of type SindriDev in the environment
func (r *Env) WithSindriDevInput(name string, value *SindriDev, description string) *Env { // sindri-dev (../../.dagger/main.go:16:6)
	assertNotNil("value", value)
	q := r.query.Select("withSindriDevInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired SindriDev output to be assigned in the environment
func (r *Env) WithSindriDevOutput(name string, description string) *Env { // sindri-dev (../../.dagger/main.go:16:6)
	q := r.query.Select("withSindriDevOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

func (r *Query) Binary() *File { // sindri-dev (../../.dagger/main.go:179:1)
	q := r.query.Select("binary")

	return &File{
		query: q,
	}
}

// ContainerOpts contains options for Query.Container
type ContainerOpts struct {
	Module string // sindri-dev (../../.dagger/main.go:46:2)
}

func (r *Query) Container(opts ...ContainerOpts) *Container { // sindri-dev (../../.dagger/main.go:43:1)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Container{
		query: q,
	}
}

// ServiceOpts contains options for Query.Service
type ServiceOpts struct {
	Backend string // sindri-dev (../../.dagger/main.go:104:2)

	Module string // sindri-dev (../../.dagger/main.go:106:2)
}

func (r *Query) Service(opts ...ServiceOpts) *Service { // sindri-dev (../../.dagger/main.go:101:1)
	q := r.query.Select("service")
	for i := len(opts) - 1; i >= 0; i-- {
		// `backend` optional argument
		if !querybuilder.IsZeroValue(opts[i].Backend) {
			q = q.Arg("backend", opts[i].Backend)
		}
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Service{
		query: q,
	}
}

func (r *Query) Tag(ctx context.Context) (string, error) { // sindri-dev (../../.dagger/main.go:174:1)
	q := r.query.Select("tag")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *Query) Test(ctx context.Context) error { // sindri-dev (../../.dagger/main.go:192:1)
	q := r.query.Select("test")

	return q.Execute(ctx)
}

func (r *Query) Version(ctx context.Context) (string, error) { // sindri-dev (../../.dagger/main.go:147:1)
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

type SindriDev struct { // sindri-dev (../../.dagger/main.go:16:6)
	query *querybuilder.Selection

	id      *ID
	tag     *string
	test    *Void
	version *string
}

func (r *SindriDev) WithGraphQLQuery(q *querybuilder.Selection) *SindriDev {
	return &SindriDev{
		query: q,
	}
}

func (r *SindriDev) Binary() *File { // sindri-dev (../../.dagger/main.go:179:1)
	q := r.query.Select("binary")

	return &File{
		query: q,
	}
}

// SindriDevContainerOpts contains options for SindriDev.Container
type SindriDevContainerOpts struct {
	Module string // sindri-dev (../../.dagger/main.go:46:2)
}

func (r *SindriDev) Container(opts ...SindriDevContainerOpts) *Container { // sindri-dev (../../.dagger/main.go:43:1)
	q := r.query.Select("container")
	for i := len(opts) - 1; i >= 0; i-- {
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Container{
		query: q,
	}
}

// A unique identifier for this SindriDev.
func (r *SindriDev) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *SindriDev) XXX_GraphQLType() string {
	return "SindriDev"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *SindriDev) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *SindriDev) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *SindriDev) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}

// SindriDevServiceOpts contains options for SindriDev.Service
type SindriDevServiceOpts struct {
	Backend string // sindri-dev (../../.dagger/main.go:104:2)

	Module string // sindri-dev (../../.dagger/main.go:106:2)
}

func (r *SindriDev) Service(opts ...SindriDevServiceOpts) *Service { // sindri-dev (../../.dagger/main.go:101:1)
	q := r.query.Select("service")
	for i := len(opts) - 1; i >= 0; i-- {
		// `backend` optional argument
		if !querybuilder.IsZeroValue(opts[i].Backend) {
			q = q.Arg("backend", opts[i].Backend)
		}
		// `module` optional argument
		if !querybuilder.IsZeroValue(opts[i].Module) {
			q = q.Arg("module", opts[i].Module)
		}
	}

	return &Service{
		query: q,
	}
}

func (r *SindriDev) Source() *Directory { // sindri-dev (../../.dagger/main.go:17:2)
	q := r.query.Select("source")

	return &Directory{
		query: q,
	}
}

func (r *SindriDev) Tag(ctx context.Context) (string, error) { // sindri-dev (../../.dagger/main.go:174:1)
	if r.tag != nil {
		return *r.tag, nil
	}
	q := r.query.Select("tag")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *SindriDev) Test(ctx context.Context) error { // sindri-dev (../../.dagger/main.go:192:1)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")

	return q.Execute(ctx)
}

func (r *SindriDev) Version(ctx context.Context) (string, error) { // sindri-dev (../../.dagger/main.go:147:1)
	if r.version != nil {
		return *r.version, nil
	}
	q := r.query.Select("version")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// AsNode returns this SindriDev as a Node.
// This is a local type conversion — no GraphQL call.
func (r *SindriDev) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}
